name: Gulp dest test
on: push
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@main
    - name: run
      uses: actions/setup-node@v1
      with:
        node-version: '10.x'
      run: ./node_modules/.bin/gulp destTest